version: 2.1
jobs:
  build:
    working_directory: ~/work
    docker:
      - image: circleci/php:7.3-node-browsers
    steps:
      - checkout
      - run: sudo composer self-update --1
      - run:
          command: composer install -n --prefer-dist
      - run:
          command: npm ci
          working_directory: work
      - run:
          command: npm run dev
          working_directory: work
      - run:
          name: php test
          command: vendor/bin/phpunit
          working_directory: work
